// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgJpLLlK1tvpAZx7ebuGZ-Xxe56lJRfBA',
    appId: '1:62126138815:android:4a5030cdaf818ac6936d0a',
    messagingSenderId: '62126138815',
    projectId: 'shop-manager-3d017',
    storageBucket: 'shop-manager-3d017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkDCcAWIHJMBoz18DYqUqt0obEd94kz90',
    appId: '1:62126138815:ios:9ec40be055580260936d0a',
    messagingSenderId: '62126138815',
    projectId: 'shop-manager-3d017',
    storageBucket: 'shop-manager-3d017.appspot.com',
    iosClientId: '62126138815-bdq1tthl1om2rocous3snrmmpqlp5lod.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAppV2',
  );
}
